### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by jsturtevant** [Azure/azure-k8s-metrics-adapter#35]
Add end to end tests that can be run in circleci workflow (and in container on local machine).  

At the least want to deploy adapter, point it at Service Bus Queue and App Insights instance that has already been provisioned for this e2e test (the test would not be responsible for creating these resources in azure but should pass those values via environment variables).  The test would:

- call validate the adapter is installed properly (`kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1"` & `kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1"`)
- install ExternalMetric CRD configured for Service Bus Queue and then make request to `kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/test/queuemessages` to get value and  compare to `az servicebus queue show --resource-group sb-external-example --namespace-name $SERVICEBUS_NS --name externalq -o json | jq .messageCount`
- install CustomMetric CRD configured for App Insights and then make request to `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/test/pods/*/custom-metric"` and make sure value is returning.

Optionally could test the whole HPA scaling flow but this much more complicated.  The above should give some basic smoke tests to make sure things are working generally.

I started the a possible e2e script here: https://github.com/Azure/azure-k8s-metrics-adapter/tree/e2e.  Using the samples ([service bus](https://github.com/Azure/azure-k8s-metrics-adapter/tree/e2e/samples/servicebus-queue) and [appinsights](https://github.com/Azure/azure-k8s-metrics-adapter/tree/e2e/samples/request-per-second)) could help guide the tests

**Comment by lee0c** [comment]
Closed with pr #58
