### ISSUE TITLE
Add support for Service Bus Queue Topic Subscriptions

### ISSUE THREAD

**Issue by jsturtevant** [Azure/azure-k8s-metrics-adapter#42]
The primary External Metric provider uses Azure Monitor to gather metrics for the Service Bus Queues.  Service Bus only outputs total Metrics for a Queue Topic.  Using the GO [service bus library](https://github.com/Azure/azure-service-bus-go/blob/master/subscription.go#L56) we can query for the Subscription [value directly](https://github.com/Azure/azure-service-bus-go/blob/1912861e4166ab293c7ca0ac7d407d1b20a55a5e/subscription.go#L56).

**Comment by jsturtevant** [comment]
Thanks.  I don't think I can assign you directly since you are not a member of the project.  

I have some idea's on how to make this extensible through the External Metric CRD but it will require a bit more work on the internal code.  There is a similar feature for Storage Bus Queues (#39) and I proposed a possible solution [here](https://github.com/Azure/azure-k8s-metrics-adapter/issues/39#issuecomment-430767176) but open to other ideas.  

How much progress have you made?  Feel free to open a PR if your far enough along and we can work through it.  Thanks!

**Comment by marc-sensenich** [comment]
I like the approach presented in #39, I agree handling CRDs per type isn't worth the overhead if avoidable. I'll bring in the work via a PR and we can iterate there.

**Comment by marc-sensenich** [comment]
@jsturtevant I've started #42, it's at the point where I'd start going down the path of converting the current Azure Monitor client to match a shared interface and then handle the CRD and configuration. I'm going to hold on that for you and we can further discuss UX of the CRD and the interface
