### ISSUE TITLE
Error when attempting to install adapter into cluster

### ISSUE THREAD

**Issue by srsrin** [Azure/azure-k8s-metrics-adapter#50]
**Describe the bug**
I'm trying to deploy the adapter to use external metrics in my cluster but this is what it says: 
"failed to download charts/azure-k8s-metrics-adapter"

**To Reproduce**
First have a cluster
kubectl create namespace custom-metrics
helm install --name my-release charts/azure-k8s-metrics-adapter --namespace custom-metrics

I made sure the helm repo is updated as well, but it seems to be pulling from the stable folder.
Also, in the readme: https://github.com/Azure/azure-k8s-metrics-adapter, you mention there is a helm chart if we use helm in our cluster but it redirects to a page not found. 

Is there functionality to deploy the adapter and external metrics using helm? 

**Kubernetes version (`kubectl version`):**
- [ ] Running on AKS
version 1.12

Thanks!

**Comment by jsturtevant** [comment]
I believe the error is because it can't find the charts locally.  The charts are not currently in the Helm repository but are hosted in this project.  If you clone this project and cd to the root of the project you should be able to run the command successfully as helm will use the local path to resolve the charts.

Thanks for the note on the broken link will update now.

**Comment by srsrin** [comment]
Ok, thank you. Another question:

instead of downloading the chart and running helm install is it possible just to apply the generated yaml file using helm in a release pipeline if we dont plan on changing the yaml?

the generated yaml file that I'm referring to that you provide if using kubectl: https://raw.githubusercontent.com/Azure/azure-k8s-metrics-adapter/master/deploy/adapter.yaml

Thanks!

**Comment by jsturtevant** [comment]
It is possible to use the generated yaml file.  There are several flags and switches (especially around auth) that are not set in the generated one at the link you reference.  For instance if you want to use Pod Identity for your authorization back to Azure you need to set those flags in the values files then generate a new yaml file, the default one shared doesn't have that set up and uses ENV variables to configure auth.

The generated yaml and helm chart are meant to be jumping place for you to get started and try it out.  You will want to look through each various files and RBAC permissions to make sure they fit your specific cluster needs.  To that end, you should either keep your own local copy of the chart (or in something like https://azure.microsoft.com/en-us/blog/azure-container-registry-public-preview-of-helm-chart-repositories-and-more/) or the generated yaml in your own repository.  Pulling from this repository with-in your own build pipeline might break your deployments.  I have tried to keep it fairly backwards compatible but bugs happen.  Same with the images that are pulled, those should be stored in ACR (or similar repo).

Hope that helps. Let me know if you have any further questions.
