### ISSUE TITLE
performanceCounters/requestsPerSecond for RPS Scaling

### ISSUE THREAD

**Issue by goodinfoconsulting** [Azure/azure-k8s-metrics-adapter#65]
Hi Everyone,

The current RPS Scaling example in the project uses a linux container (jsturtevant/metric-rps-example), that scales by reading from the **performanceCounters/requestsPerSecond** metric in the Microsoft Application Insights API.

We've tested the default code in the repo using this container, and the adapter is able to read performanceCounters/requestsPerSecond metrics from the API and scale perfectly.

However, when we use our own linux containers (so far .NET Core [Debian Linux] and JAVA [openjdk:11-jre-slim]), no performanceCounters/requestsPerSecond metrics are registered in Application Insights. No matter what time span or interval combinations are used, the Application Insights API returns Null. (We know this by browsing the Application Insights API Explorer... https://dev.applicationinsights.io).

This baffles us, since the container provided with this example is also a linux container, and it is sending performanceCounters/requestsPerSecond metrics to App Insights without any issues.

1. Is there anything special that has been done to this container to get it to send **performanceCounters/requestsPerSecond** data to Application Insights?
2. For clarity, according to the default code in the samples, is it the Code inside the container that sends telemetry to Application Insights, or is it Kubernetes?

**Comment by jsturtevant** [comment]
> Is there anything special that has been done to this container to get it to send performanceCounters/requestsPerSecond data to Application Insights?

No, the nodejs application insights library generates that value and sends it to App Insights.  

>For clarity, according to the default code in the samples, is it the Code inside the container that sends telemetry to Application Insights, or is it Kubernetes?

As mentioned in previous answer, The code that sends the data to App insights is in the container via the library.

This seems like the asp.net core library does not collect the rps or at-least not by the name `performanceCounters/requestsPerSecond`.  I am not familiar enough with the libraries or .net core to be able to say for sure.

**Comment by jsturtevant** [comment]
Digging into the ASP.NET core app insights library a bit, and found a [reference to RPS being a built in component ](https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/248#issuecomment-237042575) but did not find any docs on how to enable it.  It might be worth opening an issue there to find out how to configure it properly.  There are docs that say [performance counters are only supported in full framework](https://docs.microsoft.com/en-us/azure/azure-monitor/app/performance-counters#performance-counters-in-aspnet-core-applications).

**Comment by jsturtevant** [comment]
``
