### ISSUE TITLE
Support Self-Managed Cluster

### ISSUE THREAD

**Issue by barakAtSoluto** [Azure/azure-k8s-metrics-adapter#67]
Hi,

The Readme says this adapter is meant to be used with AKS.
Will it work with a self managed cluster (V1.11.8) provisioned by the AKS-Engine?

If not - is it possible to add support? 

Thank you!

**Comment by lee0c** [comment]
This should work with any self managed cluster that has access to Azure, so something provisioned by AKS-Engine should work well.
