### ISSUE TITLE
Custom metrics sample not working

### ISSUE THREAD

**Issue by zodraz** [Azure/azure-k8s-metrics-adapter#72]
Hi,

I am trying to make work the sample about custom metrics on Request per second, but I cannot make it work...Also I do not understand the logs and application insights correlation.

So I have this error:

I0916 10:17:31.297948       1 metric_cache.go:57] metric not found CustomMetric/default/rps
I0916 10:17:31.297953       1 provider_custom.go:100] New call to GetCustomMetric: rps
I0916 10:17:31.297958       1 appinsights.go:110] Application insights key has been provided - using Application Insights REST API.
I0916 10:17:31.297995       1 appinsights.go:186] request to:  https://api.applicationinsights.io/v1/apps/XXXXXXXXXXXXXXXXXXXX/metrics/**rps**?interval=PT30S&timespan=PT5M

What really I do not understand is that rps is the name for the K8s object not an Application Inisghts metric...Shouldn't it always fail? And be like the following request below?

curl "https://api.applicationinsights.io/v1/apps/XXXXXXXXXXXXXXXXXXXXXXX/metrics/**performanceCounters/requestsPerSecond**?timespan=PT5M&interval=PT30S&aggregation=sum" -H "x-api-key: tYYYYYYYYYYYYYYYYYYYYYY"

Thanks

**Comment by anujgeek** [comment]
@zodraz  I was able to reproduce this. Instead of creating a separate yaml for rps custom metric, put it directly inside the hpa yaml:

`  metrics:
  - type: Pods
    pods:
      metric:
        name: performanceCounters-requestsPerSecond
      target:
        type: AverageValue
        averageValue: 50`

**Comment by jsturtevant** [comment]
I believe this was caused by the image that was published image did not have support the v1alpha2 schema.  It should be available now:

`docker pull mcr.microsoft.com/k8s/metrics/adapter:v0.7.3-296`

You can find all the images version at https://mcr.microsoft.com/v2/k8s/metrics/adapter/tags/list and `latest` is tagged with the highest version.
