### ISSUE TITLE
Provide Helm chart

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-k8s-metrics-adapter#8]
Would be great to be able to deploy this via Helm.

**Comment by marc-sensenich** [comment]
If this is still open, I'd be willing to grab this issue to help out

**Comment by jsturtevant** [comment]
@marc-sensenich  That would be great.  Having a Helm chart would greatly simplify customizing the deployment.  If possible I would like to be able to have a single deployment file as it is now as well, to simplify the getting started and for those who don't want to use helm.  

I do worry about the duplication of helm charts and still having deployment file.  I am not sure if there is a way around this or what other projects do.  

Thanks for helping out!

**Comment by marc-sensenich** [comment]
I've seen other projects use `helm template` to generate a single deployment file to be used based on the Helm chart provided, which is the path I would intend on taking. This could tie back into the build pipeline for the repo to keep these in sync

**Comment by jsturtevant** [comment]
sounds good to me.  looking forward to it.  Thanks for looking into creating the helm chart 💯

**Comment by tomkerkhove** [comment]
Thanks for the tip on `helm template`, cool feature and looking forward to the helm chart.
I can test run it for you if you want.
