### ISSUE TITLE
I'm faced with an interesting auto-scaling question

### ISSUE THREAD

**Issue by eugen-nw** [Azure/azure-k8s-metrics-adapter#81]
I have the solution in place to distribute computations to containers using a Service Bus queue and have HPA setup to scale on the metric below.  It works very well, thanks very much for making it possible!

  metric:
    metricName: ActiveMessages
    aggregation: Total
    filter: EntityName eq 'requests'

The scenario that I'm faced with is that most computations complete under 2' while some take 40'.  Their ratio seems to be 22:1 in favor of the short ones.  The short requests come in sporadically, there is no way to predict when and how many will arrive.

The problem is that some of the long computations are ended prematurely - most likely because HPA terminates the container - causing them to be resumed on a different container, which makes their execution even longer.  The customer is not happy with that!

Does anyone has some suggestions on how should I go about ensuring that the long computations complete on their first attempt?  I searched and did not see any way for the container to tell HPA "leave me alone, I'm working".   If I add CPU usage as a secondary scaling criteria, won't that drive the count of containers to max, even if it is only one single long running computation that's executing?

A different solution I imagine is to save the computation's state from time to time and whenever it is forced to resume in a different container, to start from the saved state.  It's not a component I'm working on, so do not know if it is even possible.

**Comment by jsturtevant** [comment]
This is actually a [common challenge](https://github.com/kubernetes/kubernetes/issues/45509#issuecomment-557090273) that we have run into as well.  KEDA documents some of the [solutions for long running executions](https://keda.sh/concepts/scaling-deployments/#long-running-executions) as well as provides [job based scaling option](https://keda.sh/concepts/scaling-jobs/).  We have also implemented the ability to "checkpoint" the computational state as you pointed out in some cases.  

Hope this helps.

**Comment by eugen-nw** [comment]
Thanks very much James!  Is KEDA “production quality” please?  Also, how quick is KEDA to react to new messages in an Azure Service Bus queue?
