### ISSUE TITLE
The most recent version has difficulties reading the SB Queue metrics

### ISSUE THREAD

**Issue by eugen-nw** [Azure/azure-k8s-metrics-adapter#83]
I installed this morning the Adapter running `kubectl apply -f https://raw.githubusercontent.com/Azure/azure-k8s-metrics-adapter/master/deploy/adapter.yaml`

We've already used it for > 1 year, yet the output of `kubectl describe hpa` had never been as noisy as now.  Please see the attached file: [hpa.txt](https://github.com/Azure/azure-k8s-metrics-adapter/files/4042020/hpa.txt)

I just completed 50 consecutive runs of `kubectl  get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/queuemessages"` and I'm seeing 11 failures, or a success rate of 78%.  Please see in the attached file the output of that experiment: 
[verifyMessageQueueMetric.txt](https://github.com/Azure/azure-k8s-metrics-adapter/files/4042041/verifyMessageQueueMetric.txt)

I verified the other 3 AKS instances that we have in production - all running earlier versions of the 
Adapter - and none of them shows any issues getting the information.  Please see below the HPA output of the only AKS instance that experienced scaling activity recently:

![image](https://user-images.githubusercontent.com/15199814/72097482-53944100-32d1-11ea-8ed2-a3423fc18cc6.png)

I ran the `.\verifyMessageQueueMetric.ps1 -iterations 50` experiment on that particular instance of AKS and completed with *no errors*.

**Comment by jsturtevant** [comment]
Thanks for the detailed report.  What version of AKS and Adapter are you running in the various scenarios?

**Comment by eugen-nw** [comment]
Thanks very much @jsturtevant for looking into this!  For some strange reasons, that AKS instance is having some weird issues.  It'd been a pain to update the ACI Connector as well.

In the circumstances, I chose to create a brand new AKS instance and on that one the Adapter functions as greatly as it always did.
