### ISSUE TITLE
Error from server (ServiceUnavailable): the server is currently unable to handle the request

### ISSUE THREAD

**Issue by vishal8k** [Azure/azure-k8s-metrics-adapter#84]
**Describe the bug**
I'm unable to even get a response from the external metrics API after following this document "https://github.com/Azure/azure-k8s-metrics-adapter/tree/master/samples/servicebus-queue"

**To Reproduce**
Follow this document step by step "https://github.com/Azure/azure-k8s-metrics-adapter/tree/master/samples/servicebus-queue"

**Expected behavior**
After the helm installation using service-principal when executing the command `kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1" | jq ` I should be getting an output as suggested by the document. but instead I'm facing an error stating `Error from server (ServiceUnavailable): the server is currently unable to handle the request`

**Kubernetes version (`kubectl version`):**
- [x] Running on AKS
Kubernetes Version: 1.14.8
**Logs (`kubectl logs <metric adapter pod id>`)**
The helm installation was successful and below are the logs from the adapter deployment (Pod)
`I0116 12:49:36.216094       1 controller.go:40] Setting up external metric event handlers
I0116 12:49:36.216148       1 controller.go:52] Setting up custom metric event handlers
I0116 12:49:36.216528       1 controller.go:69] initializing controller
I0116 12:49:36.353905       1 main.go:104] Looking up subscription ID via instance metadata
I0116 12:49:36.359887       1 instancemetadata.go:40] connected to sub: *********************
I0116 12:49:36.416858       1 controller.go:77] starting 2 workers with 1000000000 interval
I0116 12:49:36.417062       1 controller.go:88] Worker starting
I0116 12:49:36.417068       1 controller.go:88] Worker starting
I0116 12:49:36.417074       1 controller.go:98] processing item
I0116 12:49:36.417078       1 controller.go:98] processing item
I0116 12:49:36.680065       1 serving.go:312] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
I0116 12:49:37.197936       1 secure_serving.go:116] Serving securely on [::]:6443`

**Additional context**
When I execute the command `kubectl api-versions` 
`external.metrics.k8s.io/v1beta1` is displayed. So this proves that the installation went successful. But why am I not able to hit api???

**Comment by vishal8k** [comment]
I've found a solution.

**Comment by kjdeepthi** [comment]
I'm hitting the same issue. @vishal8k could you please share the solution

**Comment by vishal8k** [comment]
@kjdeepthi For me it was the namespace. Azure metric adapter will only work if it is created under the namespace "custom-metrics". You can't create it under our custom namespaces. These guys never bothered to add this important line anywhere in the document (facepalm)

**Comment by kjdeepthi** [comment]
Thanks thats worked

**Comment by jsturtevant** [comment]
@vishal8k it is possible to install the metric adapter in a different namespace.  The only requirement is all the name spaced components must be installed together (secrets, etc).  I've seen cases where folks have installed some parts of the adapter in one namespace and other parts in a different namespace, i believe it was related to the typo in the docs (#88).

Thanks for reporting back the fix.
